#!/usr/bin/env python3
"""
Tier Classifier — Assigns maturity tiers to repos based on GitHub metadata.

Tiers:
  4 — Production-adjacent (high stars, org-owned, deployment/CI signals)
  3 — Serious projects (moderate stars or contributors, CI/tests/packaging)
  2 — Personal projects (some activity: stars >= 5, contributors >= 2, commits >= 10)
  1 — Learning/hobby (everything else, or keyword-demoted)

Also flags repos for exclusion (spark-examples clones, generated code, etc.)

Usage:
  python3 classify_tiers.py --metadata-dir metadata/
"""

import argparse
import json
import sys
from collections import Counter
from pathlib import Path


# ─────────────────────────────────────────────────────────────
# Exclusion Logic
# ─────────────────────────────────────────────────────────────

def check_exclusion(meta: dict) -> tuple[bool, str]:
    """
    Check if a repo should be excluded from the corpus entirely.
    Returns (excluded, reason).
    """
    repo_lower = meta.get("repo", "").lower()
    desc_lower = (meta.get("description") or "").lower()

    # Forks of official Spark repo
    if meta.get("is_fork", False) and "apache/spark" in repo_lower:
        return True, "spark_examples_clone"

    # Clones of official Spark examples
    if "spark-example" in repo_lower.split("/")[-1]:
        return True, "spark_examples_clone"

    # Databricks example notebooks (check for known patterns in description/topics)
    topics_lower = {t.lower() for t in meta.get("topics", [])}
    if "databricks-examples" in repo_lower or "databricks-notebook" in repo_lower:
        return True, "databricks_examples"
    if "databricks" in topics_lower and ("example" in desc_lower or "sample" in desc_lower):
        return True, "databricks_examples"

    # Generated code repos — we'd need to check file contents for this,
    # but we can flag obvious signals from description/topics
    generation_markers = {"auto-generated", "do not edit", "generated code", "autogenerated"}
    if any(marker in desc_lower for marker in generation_markers):
        return True, "generated_code"

    return False, ""


# ─────────────────────────────────────────────────────────────
# Tier Classification
# ─────────────────────────────────────────────────────────────

LEARNING_KEYWORDS = {
    "homework", "assignment", "coursework", "class project",
    "university", "course", "tutorial", "learning exercise",
}


def classify_tier(meta: dict) -> int:
    """Classify a repo into maturity tier 1-4 based on metadata."""

    # Keyword demotion check
    name_lower = meta.get("repo", "").lower().split("/")[-1]
    desc_lower = (meta.get("description") or "").lower()
    topics_lower = {t.lower() for t in meta.get("topics", [])}
    readme_kw = {k.lower() for k in meta.get("readme_keywords_matched", [])}

    is_learning = (
        any(kw in name_lower for kw in LEARNING_KEYWORDS)
        or any(kw in desc_lower for kw in LEARNING_KEYWORDS)
        or bool(topics_lower & LEARNING_KEYWORDS)
        or bool(readme_kw & LEARNING_KEYWORDS)
    )

    if is_learning:
        return 1

    stars = meta.get("stars", 0)
    contribs = meta.get("contributor_count", 0)
    commits = meta.get("commit_count", 0)
    is_org = meta.get("is_org", False)
    has_ci = meta.get("has_ci", False)
    has_tests = meta.get("has_tests", False)
    has_pkg = meta.get("has_packaging", False)
    has_deploy = meta.get("has_deployment", False)

    # Tier 4 — Production-Adjacent
    if (stars > 200 and is_org
            and (has_deploy or contribs > 10 or commits > 500)):
        return 4

    # Tier 3 — Serious Projects
    if ((stars > 50 or contribs > 3)
            and (has_ci or has_tests or has_pkg)):
        return 3

    # Tier 2 — Personal Projects
    if stars >= 5 or contribs >= 2 or commits >= 10:
        return 2

    # Tier 1 — Learning/Hobby
    return 1


# ─────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────

TIER_LABELS = {
    1: "Learning/Hobby",
    2: "Personal",
    3: "Serious",
    4: "Prod-adjacent",
}


def main():
    parser = argparse.ArgumentParser(
        description="Classify repos into maturity tiers based on GitHub metadata"
    )
    parser.add_argument(
        "--metadata-dir", type=Path, default=Path("metadata"),
        help="Directory containing per-repo metadata JSONs (default: metadata/)",
    )
    args = parser.parse_args()

    metadata_dir = args.metadata_dir.resolve()
    if not metadata_dir.exists():
        print(f"Error: Metadata directory not found: {metadata_dir}", file=sys.stderr)
        sys.exit(1)

    meta_files = sorted(metadata_dir.glob("*.json"))
    # Exclude tier-summary.json from processing
    meta_files = [f for f in meta_files if f.name != "tier-summary.json"]

    if not meta_files:
        print(f"Error: No metadata files found in {metadata_dir}", file=sys.stderr)
        sys.exit(1)

    print("═══════════════════════════════════════════════════════", file=sys.stderr)
    print("  Tier Classifier", file=sys.stderr)
    print("═══════════════════════════════════════════════════════", file=sys.stderr)
    print(f"  Metadata dir:  {metadata_dir}", file=sys.stderr)
    print(f"  Repos to classify: {len(meta_files)}", file=sys.stderr)
    print("", file=sys.stderr)

    tier_counts = Counter()
    tier_files: dict[int, int] = {1: 0, 2: 0, 3: 0, 4: 0}
    excluded_count = 0
    excluded_reasons = Counter()

    for meta_file in meta_files:
        try:
            meta = json.loads(meta_file.read_text())
        except (json.JSONDecodeError, OSError) as e:
            print(f"  Warning: Could not read {meta_file}: {e}", file=sys.stderr)
            continue

        # Check exclusion
        excluded, reason = check_exclusion(meta)
        if excluded:
            meta["excluded"] = True
            meta["exclusion_reason"] = reason
            meta["tier"] = 0  # excluded repos get tier 0
            excluded_count += 1
            excluded_reasons[reason] += 1
        else:
            meta.pop("excluded", None)
            meta.pop("exclusion_reason", None)
            tier = classify_tier(meta)
            meta["tier"] = tier
            tier_counts[tier] += 1
            tier_files[tier] += meta.get("pyspark_file_count", 0)

        # Write back with tier
        with open(meta_file, "w") as f:
            json.dump(meta, f, indent=2)

    total = sum(tier_counts.values())

    # Write tier summary
    summary = {
        "total": total,
        "excluded": excluded_count,
        "excluded_reasons": dict(excluded_reasons),
        "by_tier": {
            str(t): {"count": tier_counts[t], "pyspark_files": tier_files[t]}
            for t in [1, 2, 3, 4]
        },
    }
    summary_path = metadata_dir / "tier-summary.json"
    with open(summary_path, "w") as f:
        json.dump(summary, f, indent=2)

    # Print human-readable summary
    print("=== Corpus Summary ===", file=sys.stderr)
    print(f"Total repos: {total + excluded_count} ({excluded_count} excluded)",
          file=sys.stderr)
    for tier in [1, 2, 3, 4]:
        label = TIER_LABELS[tier]
        count = tier_counts[tier]
        files = tier_files[tier]
        print(f"  Tier {tier} ({label:15s}): {count:>5} repos, {files:>6} PySpark files",
              file=sys.stderr)
    print("", file=sys.stderr)

    if excluded_reasons:
        print("=== Excluded ===", file=sys.stderr)
        for reason, count in excluded_reasons.most_common():
            print(f"  {reason}: {count}", file=sys.stderr)
        print("", file=sys.stderr)

    print(f"  Tier summary saved to: {summary_path}", file=sys.stderr)
    print("", file=sys.stderr)
    print("Next step:", file=sys.stderr)
    print(f"  python3 scripts/pyspark-lint/aggregate_lint.py "
          f"--results-dir lint-results --metadata-dir {metadata_dir} --format both",
          file=sys.stderr)


if __name__ == "__main__":
    main()
